import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '350px',
        'sm-mobile': '472px',
        'md-tablet': '784px',
        'lg-tablet': '948px',
        'xl-desktop': '1034px',
      },
      colors: {
        "on-secondary-fixed-variant": "#245100",
        "on-primary-container": "#818583",
        "primary-container": "#181c1b",
        "tertiary-container": "#151d1b",
        "surface-container-high": "#e5e9e7",
        "on-primary-fixed-variant": "#444846",
        "inverse-primary": "#c4c7c5",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#181c1b",
        "outline-variant": "#c3c7c5",
        "on-error": "#ffffff",
        "on-background": "#181c1c",
        tertiary: "#000000",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f6faf8",
        secondary: "#8DC313",
        "surface-container-low": "#f0f4f2",
        "surface-container-highest": "#dfe3e1",
        outline: "#747876",
        error: "#ba1a1a",
        "inverse-on-surface": "#eef2f0",
        "on-surface": "#181c1c",
        "primary-fixed": "#e0e3e1",
        "surface-tint": "#5b5f5e",
        "secondary-fixed": "#8DC313",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bfc9c5",
        surface: "#f6faf8",
        "tertiary-fixed": "#dbe5e1",
        "surface-variant": "#dfe3e1",
        "on-secondary-container": "#000000",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#404946",
        "on-surface-variant": "#434846",
        "primary-fixed-dim": "#c4c7c5",
        "inverse-surface": "#2d3130",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#151d1b",
        primary: "#000000",
        "surface-container": "#ebefed",
        "secondary-fixed-dim": "#8DC313",
        "secondary-container": "#8DC313",
        "surface-dim": "#d7dbd9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#7d8682",
        background: "#f6faf8",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        margin: "64px",
      },
      fontFamily: {
        display: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        h3: ["24px", { lineHeight: "1.3", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-tech": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
